# Generated by Django 4.1.7 on 2023-02-27 19:28

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to=content.models.PostMedia.media_name),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='caption_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
